export const enum ActionLoad {
  GET_LIST_BOOKS = 'GET_BOOKS',
  GET_CATEGORY_BOOKS = 'GET_CATEGORY_BOOKS',
  LOADING = 'LOAD',
  ERROR_LOAD_LIST = 'ERROR_LOAD_LIST',
  ERROR_LOAD_CATEGORY = 'ERROR_LOAD_CATEGORY'
}
