export const enum ActionLoad {
  GET_LIST_BOOKS = 'GET_BOOKS',
  GET_CATEGORY_BOOKS = 'GET_CATEGORY_BOOKS',
  LOADING = 'LOAD',
  ERROR_LOAD_LIST = 'ERROR_LOAD_LIST',
  ERROR_LOAD_CATEGORY = 'ERROR_LOAD_CATEGORY',
  ERROR_LOAD_ID_BOOK = 'ERROR_LOAD_ID_BOOK',
  GET_ID_BOOK = 'GET_ID_BOOK',
  RESET_STATE_BOOKS = 'RESET_STATE_BOOK',
  SET_PATH = 'SET_PATH',
  RESET_LOAD_LIST = 'RESET_LOAD_LIST',
  RESPONSE = 'RESPONSE',
}
