export const TITLE_BOOK_ONE = 'Грокаем алгоритмы. Иллюстрированное пособие для програ...';
export const TITLE_BOOK_TWO = 'Грокаем алгоритмы. Иллюстрированное';
export const TITLE_BOOK_THREE = 'Грокаем алгоритмы.';
export const AUTHOR_ONE = 'Адитья Бхаргава, 2019';
export const AUTHOR_TWO = 'Адитья Бхаргава, Патрик Нимейер, 2019';
export const UPGRADE_SEARCH_RESIZE = 680;
export const ERROR_TEXT = 'Что-то пошло не так. Обновите страницу через некоторое время.';
export const CLASSNAME_BUTTON_BOOKED = 'book__submit book__submit_closed';
export const CLASSNAME_BUTTON_BOOK = 'book__submit';
export const CLASSNAME_META_BUTTON_BOOKED = 'meta-info__button meta-info__button_closed';
export const CLASSNAME_META_BUTTON_BOOK = 'meta-info__button';
export const DEFAULT_PATH_BREAD = 'Все книги';
export const NO_BOOKS_IN_CATEGORY = 'В этой категории книг ещё нет';
export const NO_BOOKS_IN_SEARCH = 'По запросу ничего не найдено';
export const BUTTON_AUTH = 'Вход'
export const LINK_REGISTRATION_AUTH = 'РЕГИСТРАЦИЯ'
export const LINK_QUESTION_AUTH = 'Нет учётной записи?'
export const LINK_RECOVER_AUTH = 'Забыли логин или пароль?'
export const TITLE_AUTH = 'Вход в личный кабинет'
export const PLACEHOLDER_PASSWORD = 'Пароль'
export const PLACEHOLDER_LOGIN = 'Логин'
export const LINK_AUTH = 'ВОЙТИ'
export const LINK_QUESTION_REG = 'Есть учётная запись?'
export const TITLE_REGISTRATION = 'Регистрация'
